"use strict";

module.exports = {
  MEDIUMTEXT: "string",
  LONGTEXT: "string",
  VARCHAR: "string",
  STRING: "string",
  TEXT: "string",
  UUID: "string",

  INT: "number",
  TINYINT: "number",
  INTEGER: "number",
  BIGINT: "number",
  FLOAT: "number",
  DOUBLE: "number",
  DECIMAL: "number",
  "INT UNSIGNED": "number",
  "TINYINT UNSIGNED": "number",
  "INTEGER UNSIGNED": "number",
  "BIGINT UNSIGNED": "number",
  "FLOAT UNSIGNED": "number",
  "DOUBLE UNSIGNED": "number",
  "DECIMAL UNSIGNED": "number",
  "INT SIGNED": "number",
  "TINYINT SIGNED": "number",
  "INTEGER SIGNED": "number",
  "BIGINT SIGNED": "number",
  "FLOAT SIGNED": "number",
  "DOUBLE SIGNED": "number",
  "DECIMAL SIGNED": "number",

  DATE: "Date",
  TIME: "Date",
  DATETIME: "Date",
  DATEONLY: "Date",
  TIMESTAMP: "Date",

  BOOLEAN: "boolean",
};
