"use strict";

module.exports = {
  VARCHAR: "string",
  STRING: "string",
  CHAR: "string",
  VARBINARY: "string",
  BINARY: "string",
  TEXT: "string",
  TINYTEXT: "string",
  MEDIUMTEXT: "string",
  LONGTEXT: "string",
  BLOB: "string",
  TINYBLOB: "string",
  MEDIUMBLOB: "string",
  LONGBLOB: "string",
  UUID: "string",
  ENUM: "string",
  SET: "string",

  BIT: "number",
  INT: "number",
  INTEGER: "number",
  TINYINT: "number",
  SMALLINT: "number",
  MEDIUMINT: "number",
  BIGINT: "number",
  REAL: "number",
  FLOAT: "number",
  DOUBLE: "number",
  "DOUBLE PRECISION": "number",
  DECIMAL: "number",
  DEC: "number",
  "INT UNSIGNED": "number",
  "TINYINT UNSIGNED": "number",
  "INTEGER UNSIGNED": "number",
  "BIGINT UNSIGNED": "number",
  "FLOAT UNSIGNED": "number",
  "DOUBLE UNSIGNED": "number",
  "DOUBLE PRECISION UNSIGNED": "number",
  "DECIMAL UNSIGNED": "number",
  "DEC UNSIGNED": "number",
  "INT ZEROFILL": "number",
  "TINYINT ZEROFILL": "number",
  "INTEGER ZEROFILL": "number",
  "BIGINT ZEROFILL": "number",
  "FLOAT ZEROFILL": "number",
  "DOUBLE ZEROFILL": "number",
  "DOUBLE PRECISION ZEROFILL": "number",
  "DECIMAL ZEROFILL": "number",
  "DEC ZEROFILL": "number",

  YEAR: "Date",
  TIME: "Date",
  DATE: "Date",
  DATETIME: "Date",
  DATEONLY: "Date",
  TIMESTAMP: "Date",

  BOOLEAN: "boolean",
  BOOL: "boolean",
};
